# Generated by Django 3.2.23 on 2025-12-05 11:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_options_organization_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legaldocument',
            options={'ordering': ['-date', 'title'], 'verbose_name': 'Правовой документ', 'verbose_name_plural': 'Правовые документы'},
        ),
        migrations.AlterModelOptions(
            name='managementstructure',
            options={'ordering': ['position', 'full_name'], 'verbose_name': 'Руководитель', 'verbose_name_plural': 'Структура руководства'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата документа'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('charter', 'Устав'), ('regulation', 'Положение'), ('order', 'Приказ'), ('decree', 'Постановление'), ('agreement', 'Договор'), ('other', 'Прочее')], default='other', max_length=50, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='legal_documents/%Y/%m/%d/', verbose_name='Файл документа'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер документа'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='title',
            field=models.CharField(default='', max_length=500, verbose_name='Название документа'),
        ),
        migrations.AddField(
            model_name='managementstructure',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата назначения'),
        ),
        migrations.AddField(
            model_name='managementstructure',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='managementstructure',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='managementstructure',
            name='full_name',
            field=models.CharField(default='', max_length=200, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='managementstructure',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер приказа'),
        ),
        migrations.AddField(
            model_name='managementstructure',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='managementstructure',
            name='position',
            field=models.CharField(default='', max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to='organizations.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='managementstructure',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_structures', to='organizations.organization', verbose_name='Организация'),
        ),
    ]
